


#before_script:
#  GITHUB

script:
  - echo 'Hello World'
  - zip -r latest-plugin *
  - ls -al

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "latest-plugin-zip"
  overwrite: true
  skip_cleanup: true
  draft: true