##
## Simple script to build a zip file of the whole repository
##

script:
# debug  - echo 'Hello World'
  - zip -r master *
# debug  - ls -al

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "master.zip"
  overwrite: true
  skip_cleanup: true
  draft: true