


#before_script:
#  GITHUB

script:
  - echo 'Hello World'
  - zip -r master *
  - ls -al

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "master.zip"
  overwrite: true
  skip_cleanup: true
  draft: true